version: "3.9"

services:
  database:
    container_name: boilerplate_logging_database
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: boilerplate_logging_live
    ports:
      - "3403:3306"
    volumes:
      - "logging_local_mysql_data:/var/lib/mysql"
    networks:
      - boilerplate_microservices_network

  app:
    container_name: boilerplate_logging_service
    image: node:20.13
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      APP_ENV: local
      DATABASE_URL: mysql://root:password@host.docker.internal:3403/boilerplate_logging_live
      KAFKA_BROKER: host.docker.internal:9092
    ports:
      - "5003:3000"
    depends_on:
      - database
    working_dir: /var/app/current
    volumes:
      - "./:/var/app/current"
    networks:
      - boilerplate_microservices_network

networks:
  boilerplate_microservices_network:
    driver: bridge

volumes:
  logging_local_mysql_data: